### ISSUE TITLE
Error creating database

### ISSUE THREAD

**Issue by ss13ms110** [Lean5/arangodb_ecto#1]
I am using `mix ecto.create` to create database but getting the following error
** (Mix) The database for RegUser.Repo couldn't be created: %HTTPoison.Error{id: nil, reason: :econnrefused}

I am new to elixir and want to use ArangoDB via arango_ecto adapter. 
Configurations in dev.exs file are:

# Configure your database
config :reg_user, RegUser.Repo,
  adapter: ArangoDB.Ecto,
  username: "root",
  password: "password",
  database: "reg_user",
  hostname: "10.0.21.6",
  port: 8529,
  pool_size: 10

Please help me to get through this.

Thanks in advance

**Comment by mpoeter** [comment]
The parameters in the Repo config have different names:
* `hostname` should be `host`
* `database` should be `database_name`

I know that this is inconsistent with the standard Ecto repository implementations and I want to change that at some point, but for now you have to define `host` and `database_name`.

Also note that the `pool_size` parameter is not used since this adapter does not use a connection pool.

**Comment by ss13ms110** [comment]
Thanks a lot. It worked
